version: '3'

services: 
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    ports: 
      - 8080:80
    environment:
      PGADMIN_HOST: postgres