version: '3'

services:
  mongo-container:
    image: mongo:3.4
    command: mongod
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
    volumes:
      - '/data/mongo:/data/db'
